name: Deploy functions to Supabase

on:
  push:
    branches: ['master']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

# Allow one concurrent deployment
concurrency:
  group: 'functions'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: functions
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
      - name: Deploy to Supabase
        run: supabase functions deploy --project-ref $PROJECT_ID --no-verify-jwt --import-map supabase/import_map.json
